version: '3.9'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - bank-app
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - bank-app
  account:
    build: ./account
    ports:
      - "8080:8080"
      - "8082:8082"
    depends_on:
      - kafka
    networks:
      - bank-app
    environment:
      CUSTOM_KAFKA_URL: kafka:9092
  transaction:
    build: ./transaction
    ports:
      - "8081:8081"
      - "8083:8083"
    depends_on:
      - account
    networks:
      - bank-app
    environment:
      CUSTOM_KAFKA_URL: kafka:9092

networks:
  bank-app:
    name: bank-app
    driver: bridge